### ISSUE TITLE
pip tries to install/uninstall in system directory

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alibuild#396]
Building FairRoot from scratch in empty directory with 
`alibuild/aliBuild --defaults o2 build FairRoot`

Build fails at `Building Python-modules@1.0`

```bash
+ pip install --install-option=--prefix=/src/src/alisw/sw/INSTALLROOT/a6c6f2247c40337e74935e041d4bb0145a746d3d/ubuntu1404_x86-64/Python-modules/1.0-1 certifi==2015.9.6.2
Downloading/unpacking certifi==2015.9.6.2
Installing collected packages: certifi
  Found existing installation: certifi 2016.9.26
    Uninstalling certifi:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1432, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 599, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1845, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 296, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/certifi-2016.9.26.dist-info/DESCRIPTION.rst'
```

Although the install prefix is given as an option to pip it tries to do the changes in the system directory.

In the first attempt, certifi was missing and I have installed this module in the system. But it's not the required version.

**Comment by ktf** [comment]
For the record:

```bash
```bash
some bash script
``\` 
```

allows you to specify a nicely formatted (and syntax highlighted) code-block.

**Comment by matthiasrichter** [comment]
ah, good to know, thanks

**Comment by dberzano** [comment]
I believe we have fixed this in the meanwhile by using `PYTHONUSERBASE` instead of `pip install --prefix`. @matthiasrichter please reopen (in alidist) in case I am wrong!

**Comment by matthiasrichter** [comment]
Hi Dario, I have not checked this recently, but if you have done changes which potentially solve this problem it's fine.
