### ISSUE TITLE
Package "in development mode" can't be built inside docker container

### ISSUE THREAD

**Issue by ghost** [alisw/alibuild#454]
because repository refers to host path:

```
+ '[' X/sw/slc5_x86-64/ROOT/v5-34-30-alice7-1 = X ']'
+ [[ RELWITHDEBINFO == COVERAGE ]]
+ cmake /sw/SOURCES/AliPhysics/slc5_x86-64/0 -DCMAKE_INSTALL_PREFIX=/sw/slc5_x86-64/AliPhysics/slc5_x86-64-1 -DROOTSYS=/sw/slc5_x86-64/ROOT/v5-34-30-alice7-1 -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DALIEN=/sw/slc5_x86-64/AliEn-Runtime/v2-19-le-1 -DALIROOT=/sw/slc5_x86-64/AliRoot/291f4ef608b91d9125f12fb1d8fa8a1af83a5a24-1
-- The CXX compiler identification is GNU 4.9.3
-- The C compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /sw/slc5_x86-64/GCC-Toolchain/v4.9.3-alice3-1/bin/c++
-- Check for working CXX compiler: /sw/slc5_x86-64/GCC-Toolchain/v4.9.3-alice3-1/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /sw/slc5_x86-64/GCC-Toolchain/v4.9.3-alice3-1/bin/cc
-- Check for working C compiler: /sw/slc5_x86-64/GCC-Toolchain/v4.9.3-alice3-1/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake platform: Linux-2.6.18-398.el5
-- Build folder: /sw/BUILD/8b046d60b16f4d390531a2528c32a95370ecec84/AliPhysics
-- Source folder: /sw/SOURCES/AliPhysics/slc5_x86-64/0
-- Installation folder: /sw/slc5_x86-64/AliPhysics/slc5_x86-64-1
-- Build type: RELWITHDEBINFO (-O2 -g -DNDEBUG)
-- Found Git: /usr/bin/git (found version "1.7.12.4") 
CMake Error at cmake/CheckGitVersion.cmake:175 (message):
  Could not retrieve serial number: error: object directory
  /home/$USER/sources/alisw/sw/MIRROR/aliphysics/objects does not exist;
  check .git/objects/info/alternates.

  fatal: bad object 046dbb02fe7a1bf8ce0178cb09b257713514bccf
Call Stack (most recent call first):
  CMakeLists.txt:65 (include)


-- Configuring incomplete, errors occurred!
See also "/sw/BUILD/8b046d60b16f4d390531a2528c32a95370ecec84/AliPhysics/CMakeFiles/CMakeOutput.log".
```

**Comment by BerserkerTroll** [comment]
Yes, it is possible to solve this by mounting the path as a volume into the docker container using the option `-v /home/$USER/sources/alisw/sw/MIRROR/aliphysics/objects:/home/$USER/sources/alisw/sw/MIRROR/aliphysics/objects`, but the question is why `aliBuild` doesn't do it by default???

**Comment by ktf** [comment]
This is indeed something we should fix.

**Comment by BerserkerTroll** [comment]
@ktf mountin a volume doesn't solve all the problems:
```
DEBUG:AliPhysics:slc5_x86-64: Package AliPhysics was correctly compiled. Moving to next one.
Traceback (most recent call last):
  File "/home/$USER/.local/bin/aliBuild", line 1323, in <module>
    doMain()
  File "/home/$USER/.local/bin/aliBuild", line 996, in doMain
    unlink(hashFile)
OSError: [Errno 13] Permission denied: '/home/$USER/sources/alisw/sw/slc5_x86-64/AliPhysics/slc5_x86-64-2/.build-hash'
```

**Comment by ktf** [comment]
Please try with 1.8.9 as a bunch of things have been fixed in the docker support.
