### ISSUE TITLE
Logging Errors during build

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#458]
During the build, I get regular "logging errors" from python that look like the following:

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/qon/data/Daten/clones/alibuild/alibuild_helpers/log.py", line 73, in format
    record.msg = record.msg.encode('ascii','replace')
AttributeError: 'bytes' object has no attribute 'encode'
Call stack:
  File "./alibuild/aliBuild", line 1337, in <module>
    doMain()
  File "./alibuild/aliBuild", line 1015, in doMain
    createDistLinks(spec, specs, args, "dist", "full_requires")
  File "./alibuild/aliBuild", line 137, in createDistLinks
    source=source))
  File "./alibuild/aliBuild", line 58, in execute
    printer(output)
Message: b''
Arguments: ()

It seems not to affect the build itself.
I am running current alibuild master (commit 0c835c04ccbca4dce21f9fb4b2d37f09859ff26e) on Gentoo, which is an "unsupported architecture".

**Comment by ktf** [comment]
Thanks. This is an issue with python3, but as you say it should be harmless. As soon as we get a bit of time it will be cleaned up.

**Comment by dberzano** [comment]
They are fixed in #466, will merge it soon.
