### ISSUE TITLE
Error when calling aliBuild without any arguments

### ISSUE THREAD

**Issue by kreisl** [alisw/alibuild#620]
I noticed that when I call aliBuild without any arguments I get a strange error. When I run aliBuild architecture the command gives me the right result. The issue can be fixed by adding the line `args.architecture = detectArch()` to the file alibuild_helpers/args.py after line 293. Not sure if this is an intended behaviour, or not.
I am using
aliBuild version: 1.5.5 (slc7_x86-64) on CentOS Linux 7 (Core)
Here is the error log.
```
$ aliBuild
Traceback (most recent call last):
  File "/USER/.local/bin/aliBuild", line 128, in <module>
    doMain(args, parser)
  File "/USER/.local/bin/aliBuild", line 43, in doMain
    "ALIBUILD_ARCHITECTURE": args.architecture
AttributeError: 'Namespace' object has no attribute 'architecture'
Traceback (most recent call last):
  File "/USER/.local/bin/aliBuild", line 135, in <module>
    report_exception(e)
  File "/USER/.local/lib/python3.7/site-packages/alibuild_helpers/analytics.py", line 106, in report_exception
    exf = "1")
  File "/USER/.local/lib/python3.7/site-packages/alibuild_helpers/analytics.py", line 73, in report
    architecture = os.environ["ALIBUILD_ARCHITECTURE"]
  File "/PYTHON_LIB_PATH/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'ALIBUILD_ARCHITECTURE'
```

**Comment by bdrum** [comment]
The same issue for any aliBuild command:

~~~bash
aliBuild version
Traceback (most recent call last):
  File "/home/bdrum/.local/bin/aliBuild", line 128, in <module>
    doMain(args, parser)
  File "/home/bdrum/.local/bin/aliBuild", line 45, in doMain
    os.environ.update(ENVIRONMENT_OVERRIDES)
  File "/usr/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/usr/lib/python3.8/os.py", line 678, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.8/os.py", line 748, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "/home/bdrum/.local/bin/aliBuild", line 135, in <module>
    report_exception(e)
  File "/home/bdrum/.local/lib/python3.8/site-packages/alibuild_helpers/analytics.py", line 104, in report_exception
    report("exception",
  File "/home/bdrum/.local/lib/python3.8/site-packages/alibuild_helpers/analytics.py", line 73, in report
    architecture = os.environ["ALIBUILD_ARCHITECTURE"]
  File "/usr/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'ALIBUILD_ARCHITECTURE'
~~~

I've tried to reinstall it, 

~~~bash
pip install --upgrade --force-reinstall aliBuild
~~~
but it didn't help.


Also I've created env ALIBUILD_ARCHITECTURE by hand, but aliBuild doesn't see it anyway.

Something has happened, because alienv and grid works fine.

Perhaps the reason in new version of python that I've changed after aliBuild installation from 3.6 to 3.8...

**Comment by ktf** [comment]
Can you try with:

```
pip install --upgrade --force-reinstall git+https://github.com/alisw/alibuild@master
```

and see if that works?

**Comment by kreisl** [comment]
This seems to work for me. aliBuild version now says `aliBuild version: LAST-TAG (slc7_x86-64)`. And I don't get the error about the missing `ALIBUILD_ARCHITECTURE` anymore

**Comment by bdrum** [comment]
For me it also works. Thanks!
