### ISSUE TITLE
Fallback to latin-1 when utf-8 does not work...

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#655]
Apparently sometimes on some systems we get:

```
==> GEANT4 is being built (use --debug for full output) [25%]
..Traceback (most recent call last):
  File "/usr/local/bin/aliBuild", line 132, in <module>
    doMain(args, parser)
  File "/usr/local/bin/aliBuild", line 82, in doMain
    printer, msg, code = doBuild(args, parser)
  File
"/usr/local/lib/python3.9/site-packages/alibuild_helpers/build.py",
line 1172, in doBuild
    err = execute("%s -e -x %s/build.sh 2>&1" % (BASH, scriptDir),
  File
"/usr/local/lib/python3.9/site-packages/alibuild_helpers/cmd.py", line
16, in execute
    printer(to_unicode(line).strip("\n")) # yield line
  File
"/usr/local/lib/python3.9/site-packages/alibuild_helpers/utilities.py",
line 38, in to_unicode
    return s.decode("utf-8")  # to get newlines as such and not as
escaped \n
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position
41: invalid continuation byte
```

This is due the fact the text is most likely encoded in latin1 and we use unicode to decode.

**Comment by ktf** [comment]
Fixed by #656.
