### ISSUE TITLE
Python version for alibuild/master

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#660]
Using alibuild/master fails for me with
```
Traceback (most recent call last):
  File "/home/qon/alice/alibuild/aliBuild", line 132, in <module>
    doMain(args, parser)
  File "/home/qon/alice/alibuild/aliBuild", line 82, in doMain
    printer, msg, code = doBuild(args, parser)
  File "/home/qon/alice/alibuild/alibuild_helpers/build.py", line 555, in doBuild
    err = execute(cmd, h)
  File "/home/qon/alice/alibuild/alibuild_helpers/cmd.py", line 16, in execute
    printer("%s", to_unicode(line).strip("\n"))
TypeError: __call__() takes 2 positional arguments but 3 were given
```
while 1.7.3 works well. I am using python 3.7. Any ideas?

**Comment by ktf** [comment]
@TimoWilken can you have a look?

**Comment by TimoWilken** [comment]
@davidrohr @pzhristov It seems to be working locally for me on Python 3.9.2 and 2.7.18. Which packages are you building?

**Comment by davidrohr** [comment]
O2

**Comment by pzhristov** [comment]
I am building AliPhysics
