### ISSUE TITLE
cannot install alibuild in Mac. Crash when building XRootD@v3.3.6-alice2

### ISSUE THREAD

**Issue by raquishp** [alisw/alibuild#707]
Dear experts,

As alidock will not be supported, I'm trying to install alibuild to be able to use AliPhysics on macOS Big Sur 11.4. However, following the documentation, when running:

````
git clone https://github.com/alisw/alidist.git
alibuild/aliBuild build AliRoot
alibuild/alienv enter AliRoot/latest
aliroot -b
````
or running:
`pip install alibuild` or `pip3 install alibuild`

I get the following error:

````
==> Building XRootD@v3.3.6-alice2
==> XRootD is being built (use --debug for full output): failed    
ERROR: Error while executing /Users/myuser/alice-sw/sw/SPECS/osx_x86-64/XRootD/v3.3.6-alice2-local1/build.sh on `myuser-MacBook-Pro.local'.
ERROR: Log can be found in /Users/myuser/alice-sw/sw/BUILD/XRootD-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /Users/myuser/alice-sw/sw/BUILD/XRootD-latest/XRootD.
ERROR: AliRoot/latest was not found
````
here is the error log file https://cernbox.cern.ch/index.php/s/0D2dFsFy9eRspGh

can you please help me understand what the problem is?

Thanks

**Comment by ktf** [comment]
Which documentation is this? Looks like you are not following:

https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-macos.html

**Comment by raquishp** [comment]
I followed that as well. And I run into this problem when running:
`brew install alisw/system-deps/o2-full-deps alisw/system-deps/alibuild`
the `o2-full-deps` part works fine, but it crashes when running `brew install alisw/system-deps/alibuild` with the following error: 
````
==> /usr/local/Cellar/alibuild/1.8.6/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/alibuild--PyYAML-20210720-4
Last 15 lines from /Users/raquelquishpe/Library/Logs/Homebrew/alibuild/07.pip:
  ERROR: Failed building wheel for PyYAML
Failed to build PyYAML
ERROR: Could not build wheels for PyYAML which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/alibuild/1.8.6/libexec/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/alibuild/1.8.6/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/alibuild/1.8.6/libexec/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 360, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for PyYAML which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/Cellar/alibuild/1.8.6/libexec/bin/python3 -m pip install --upgrade pip' command.
Removed build tracker: '/private/tmp/pip-req-tracker-roor_svp'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/alisw/homebrew-system-deps/issues

````

**Comment by ktf** [comment]
Can you try instally libyaml by hand with:

```
brew install libyaml
```

and then try again?

**Comment by ktf** [comment]
Looks like this is a problem with non-updated homebrew python installation. Something which fixed it for someone else:

```
brew uninstall alibuild # if any
brew uninstall python@3.8 python@3.9
brew untap alisw/system-deps
brew tap alisw/system-deps
brew install o2-full-deps
brew cleanup
brew install alibuild
```

**Comment by ktf** [comment]
Closing this. Please reopen if you still do not manage.

**Comment by raquishp** [comment]
Dear Giulio,

Thanks for the help. It didn't work for me, but what I tried at the end and worked was to uninstall python, homebrew and macports, and then install homebrew and python with brew.

Cheers,
Raquel
________________________________
