### ISSUE TITLE
Compilation of GEANT4 fails with python error

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#738]
Compiling GEANT4 with alibuild/master, I am getting the following python error:
```
Traceback (most recent call last):
  File "/home/qon/alice/alibuild/aliBuild", line 133, in <module>
    doMain(args, parser)
  File "/home/qon/alice/alibuild/aliBuild", line 84, in doMain
    sys.exit(doBuild(args, parser))
  File "/home/qon/alice/alibuild/alibuild_helpers/build.py", line 1026, in doBuild
    err = execute("%s -e -x %s/build.sh 2>&1" % (BASH, scriptDir),
  File "/home/qon/alice/alibuild/alibuild_helpers/cmd.py", line 50, in execute
    for line in lines_iterator:
  File "/usr/lib/python-exec/python3.9/../../../lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 1678: invalid continuation byte
```
Any idea? Is that from the parsing of the log file or what?

**Comment by davidrohr** [comment]
Indeed, it was a problem with alibuild parsing the output of the geant build script.
I disabled that part at /home/qon/alice/alibuild/alibuild_helpers/cmd.py line 50 and then it went through.

**Comment by ktf** [comment]
@TimoWilken could you have a look? In other places the solution we had for this is merely:

```
      try:
        s = s.decode("utf-8")  # to get newlines as such and not as escaped \n
      except:
        s = s.decode("latin-1")  # Workaround issue with some special characters of latin-1 which are not understood by unicode
```

**Comment by ktf** [comment]
however I am not sure here where it needs to be applied, since the code itself is in python, AFAICT.
