### ISSUE TITLE
A build results in formatting error

### ISSUE THREAD

**Issue by mborisyak** [alisw/alibuild#887]
Dear alibuild developers,

I was using `aliBuild` for compiling [FairShip](https://github.com/ShipSoft/shipdist) and encountered the following error:
```bash
$ aliBuild build FairShip --config-dir shipdist/ --defaults release --always-prefer-system
Traceback (most recent call last):
  File "/home/max/opt/pyenv/versions/py3/bin/aliBuild", line 130, in <module>
    doMain(args, parser)
  File "/home/max/opt/pyenv/versions/py3/bin/aliBuild", line 83, in doMain
    doBuild(args, parser)
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/build.py", line 490, in doBuild
    getPackageList(packages                = packages,
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/utilities.py", line 469, in getPackageList
    requested_version = resolve_version(spec, defaults, "unavailable", "unavailable")
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/utilities.py", line 126, in resolve_version
    return spec["version"] % {
TypeError: unsupported operand type(s) for %: 'float' and 'dict'
```
The error was provoked by [the following dependency](https://github.com/ShipSoft/shipdist/blob/main/termcap.sh#L2):
```
package: termcap
version: 1.0
```
It seems like the version was parsed as float.

Forcing `str` in [alibuild_helpers/utilities.py:126](https://github.com/alisw/alibuild/blob/master/alibuild_helpers/utilities.py#L126) does solve the problem:
```python
return str(spec['version']) % {
  ...
}
```
however, I'm not sure if it is the right way to fix the issue.

Sincerely,
Maxim.

**Comment by mborisyak** [comment]
Thank you!
An alternative would be to raise an error, but you are right --- converting the version into a string is easier and more intuitive.
